In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in ./.local/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in ./.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in ./.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /opt/tljh/user/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

In [11]:
import pandas as pd

In [18]:
df = pd.read_csv('shared_data_read_only/Geography-Mapping/ZIP_TRACT_122023.CSV')

In [20]:
display(df)

,ZIP,TRACT,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,501,36103158607,HOLTSVILLE,NY,0.000000,1.000000,0.000000,1.000000
1,601,72001956800,ADJUNTAS,PR,0.014530,0.012469,0.042683,0.015121
2,601,72113071700,ADJUNTAS,PR,0.158291,0.199501,0.128049,0.160094
3,601,72001956600,ADJUNTAS,PR,0.180513,0.351621,0.378049,0.196259
4,601,72001956700,ADJUNTAS,PR,0.646667,0.436409,0.451220,0.628527
...,...,...,...,...,...,...,...,...
188841,99925,2198000200,KLAWOCK,AK,1.000000,0.000000,1.000000,1.000000
188842,99926,2198940100,METLAKATLA,AK,1.000000,0.000000,1.000000,1.000000
188843,99927,2198000100,POINT BAKER,AK,0.000000,0.000000,1.000000,1.000000
188844,99928,2130000101,WARD COVE,AK,0.000000,0.000000,1.000000,1.000000
188845,99929,2275000300,WRANGELL,AK,1.000000,1.000000,1.000000,1.000000

In [21]:
FILTER_PA = df[df['USPS_ZIP_PREF_STATE']=='PA']

In [22]:
display(FILTER_PA)

,ZIP,TRACT,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
24994,15001,42007605002,ALIQUIPPA,PA,0.002607,0.001078,0.000000,0.002480
24995,15001,42007604901,ALIQUIPPA,PA,0.109431,0.092672,0.102778,0.108464
24996,15001,42003449000,ALIQUIPPA,PA,0.000290,0.000000,0.000000,0.000270
24997,15001,42007602900,ALIQUIPPA,PA,0.009269,0.000000,0.005556,0.008733
24998,15001,42007604500,ALIQUIPPA,PA,0.109663,0.036638,0.063889,0.105121
...,...,...,...,...,...,...,...,...
33896,19611,42011002200,READING,PA,0.000000,0.001898,0.000000,0.000192
33897,19611,42011002700,READING,PA,0.092862,0.028463,0.000000,0.082708
33898,19611,42011002600,READING,PA,0.256881,0.096774,0.054187,0.232737
33899,19611,42011002900,READING,PA,0.206086,0.161290,0.187192,0.200808
33900,19612,42011000600,READING,PA,1.000000,1.000000,1.000000,1.000000

In [23]:
zip_codes = [
    19124, 19134, 19140, 19133, 19120,
    19141, 19134, 19125, 19122, 19124,
    19132, 19126, 19123, 19144, 19012,
    19138, 19121
]

# Convert the list to a set to remove duplicates
zip_codes = set(zip_codes)

# Filter the DataFrame to include only the rows with zip codes in the list
FILTER_ZIP = df[df['ZIP'].isin(zip_codes)]

display(FILTER_ZIP)

,ZIP,TRACT,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
31913,19012,42091202201,CHELTENHAM,PA,0.651793,0.748201,0.971831,0.665074
31914,19012,42091202202,CHELTENHAM,PA,0.348207,0.251799,0.028169,0.334926
32529,19120,42101028901,PHILADELPHIA,PA,0.052378,0.059316,0.020548,0.052044
32530,19120,42101029100,PHILADELPHIA,PA,0.039723,0.072575,0.034247,0.041419
32531,19120,42101027402,PHILADELPHIA,PA,0.095118,0.062805,0.099315,0.093424
...,...,...,...,...,...,...,...,...
32902,19144,42101024200,PHILADELPHIA,PA,0.131427,0.157246,0.155487,0.134759
32903,19144,42101980100,PHILADELPHIA,PA,0.000276,0.000725,0.000775,0.000341
32904,19144,42101024600,PHILADELPHIA,PA,0.055363,0.111594,0.065917,0.058938
32905,19144,42101024400,PHILADELPHIA,PA,0.052484,0.049275,0.084917,0.055186
32906,19144,42101020600,PHILADELPHIA,PA,0.044203,0.012319,0.009306,0.039633